export const AVATARS_CONSTRAINT_AVATAR_ID_PK =
  'AVATARS_CONSTRAINT_AVATAR_ID_PK';

export const AVATARS_CONSTRAINT_USER_ID_FK = 'AVATARS_CONSTRAINT_USER_ID_FK';

export const AVATARS_CONSTRAINT_UNIQUE_CURRENT_USER =
  'AVATARS_CONSTRAINT_UNIQUE_CURRENT_USER';
