export const USERS_CONSTRAINT_USER_ID_PK = 'USERS_CONSTRAINT_USER_ID_PK';

export const USERS_CONSTRAINT_USERNAME_UQ = 'USERS_CONSTRAINT_USERNAME_UQ';

export const USERS_CONSTRAINT_EMAIL_UQ = 'USERS_CONSTRAINT_EMAIL_UQ';
