export const CONSTRAINT_USERS_USER_ID_PK = 'CONSTRAINT_USERS_USER_ID_PK';

export const CONSTRAINT_USERS_USERNAME_UQ = 'CONSTRAINT_USERS_USERNAME_UQ';

export const CONSTRAINT_USERS_EMAIL_UQ = 'CONSTRAINT_USERS_EMAIL_UQ';
