// wallets

export const WALLET_CONSTRAINT_WALLET_ID_PK = 'WALLET_CONSTRAINT_WALLET_ID_PK';

export const WALLET_CONSTRAINT_UNIQUE_USERID_CURRENCY =
  'WALLET_CONSTRAINT_UNIQUE_USERID_CURRENCY';

export const WALLET_CONSTRAINT_USER_ID_FK = 'WALLET_CONSTRAINT_USER_ID_FK';

export const WALLET_CONSTRAINT_CHECK_BALANCE =
  'WALLET_CONSTRAINT_CHECK_BALANCE';

// wallet operations

export const WALLET_OPERATIONS_CONSTRAINT_WALLET_OPERATION_ID_PK =
  'WALLET_OPERATIONS_CONSTRAINT_WALLET_OPERATION_ID_PK';

export const WALLET_OPERATIONS_CONSTRAINT_CHECK_AMOUNT =
  'WALLET_OPERATIONS_CONSTRAINT_CHECK_AMOUNT';

export const WALLET_OPERATIONS_CONSTRAINT_WALLET_ID_FK =
  'WALLET_OPERATIONS_CONSTRAINT_WALLET_ID_FK';

export const WALLET_OPERATIONS_CONSTRAINT_WALLET_TRANSFER_ID_FK =
  'WALLET_OPERATIONS_CONSTRAINT_WALLET_TRANSFER_ID_FK';

// wallet transfers

export const WALLET_TRANSFERS_CONSTRAINT_WALLET_TRANSFER_ID_PK =
  'WALLET_TRANSFERS_CONSTRAINT_WALLET_TRANSFER_ID_PK';

export const WALLET_TRANSFERS_CONSTAINT_FROM_WALLET_ID_FK =
  'WALLET_TRANSFERS_CONSTAINT_FROM_WALLET_ID_FK';

export const WALLET_TRANSFERS_CONSTAINT_TO_WALLET_ID_FK =
  'WALLET_TRANSFERS_CONSTAINT_TO_WALLET_ID_FK';

export const WALLET_TRANSFERS_CONSTRAINT_UNIQUE_IDEMPOTENCY_KEY =
  'WALLET_TRANSFERS_CONSTRAINT_UNIQUE_IDEMPOTENCY_KEY';
