export const WALLET_CONSTRAINT_WALLET_ID_PK = 'WALLET_CONSTRAINT_WALLET_ID_PK';

export const WALLET_OPERATIONS_CONSTRAINT_WALLET_OPERATION_ID_PK =
  'WALLET_OPERATIONS_CONSTRAINT_WALLET_OPERATION_ID_PK';

export const WALLET_CONSTRAINT_UNIQUE_USERID_CURRENCY =
  'WALLET_CONSTRAINT_UNIQUE_USERID_CURRENCY';

export const WALLET_CONSTRAINT_USER_ID_FK = 'WALLET_CONSTRAINT_USER_ID_FK';

export const WALLET_CONSTRAINT_CHECK_BALANCE =
  'WALLET_CONSTRAINT_CHECK_BALANCE';

export const WALLET_OPERATIONS_CONSTRAINT_CHECK_AMOUNT =
  'WALLET_OPERATIONS_CONSTRAINT_CHECK_AMOUNT';

export const WALLET_OPERATIONS_CONSTRAINT_WALLET_ID_FK =
  'WALLET_OPERATIONS_CONSTRAINT_WALLET_ID_FK';
